name: Compare ACS Scans
on:
  # schedule:
  #   - cron:  '00 11 * * SUN'
  push:
    branches: [dev]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: "Download artifact"
        continue-on-error: true
        run: |
          OTHER_REPO="bcgov/security-scan-jira"
          WF_NAME="compare-acs-scans.yml"
          ARTIFACT_NAME="last-acs-results"
          RUN_ID=`gh run --repo ${OTHER_REPO} list --workflow ${WF_NAME} --json databaseId --jq .[1].databaseId`
          mkdir last_acs_scans
          echo "Downloading ${ARTIFACT_NAME} from ${OTHER_REPO} with run ID ${RUN_ID}"
          gh run --repo ${OTHER_REPO} download ${RUN_ID} -n ${ARTIFACT_NAME} -D last_acs_scans
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: '3.9'
          architecture: 'x64'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install PyYAML requests
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Run python Script
        run: python .github/compare-acs-scans.py
        env:
          JIRA_EMAIL: ${{ secrets.JIRA_EMAIL }}
          JIRA_API_KEY: ${{ secrets.JIRA_API_KEY }}
          ACS_API_KEY: ${{ secrets.ACS_API_KEY }}
          ACCEPTED_VULNERABILITIES: HIGH,CRITICAL
          USE_TEST_DATA: true
          JIRA_OPERATION: NONE
          JIRA_PUT_ID: ABC-123
          START_FRESH: false
      - name: Upload Old Scan Results
        uses: actions/upload-artifact@v2
        with:
          name: last-acs-results
          path: ./last_acs_results.json
      - name: Upload ticket
        uses: actions/upload-artifact@v2
        with:
          name: acs-ticket-data
          path: ./acs_ticket_data.json
